import {useEffect,useRef,useState} from 'react';
import {Download,Package,Search,Upload,Check} from 'lucide-react';
import {fetchExtension,parseExtension,searchExtensions,themeId,type Extension,type Listing} from './extensions';
import './extensions.css';

export function ExtensionsPanel({items,onChange,theme,onTheme}:{items:Extension[];onChange:(items:Extension[])=>void;theme:string;onTheme:(theme:string)=>void}){
  const [view,setView]=useState('discover');const [query,setQuery]=useState('');const [category,setCategory]=useState('Themes');
  const [results,setResults]=useState<Listing[]>([]);const [loading,setLoading]=useState(false);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const upload=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(view!=='discover')return;let current=true;setLoading(true);setError('');const timer=setTimeout(()=>{
    searchExtensions(query,category).then(data=>{if(current)setResults(data);}).catch(e=>{if(current)setError(String(e));}).finally(()=>{if(current)setLoading(false);});
  },350);return()=>{current=false;clearTimeout(timer);};},[query,category,view]);
  function commit(next:Extension[]){onChange(next);}
  async function install(listing:Listing){const id=`${listing.namespace}.${listing.name}`;setBusy(id);setError('');setNotice('');try{const ext=await fetchExtension(listing);commit([...items.filter(x=>x.id.toLowerCase()!==ext.id.toLowerCase()),ext]);setNotice(`${ext.name} installed. ${ext.themes.length?'Choose its theme below.':'Snippets are ready in editor suggestions.'}`);}catch(e){setError(String(e));}finally{setBusy('');}}
  async function importFile(file:File){setBusy('import');setError('');try{if(file.size>16*1024*1024)throw new Error('Choose a VSIX smaller than 16 MB.');const ext=parseExtension(new Uint8Array(await file.arrayBuffer()));commit([...items.filter(x=>x.id.toLowerCase()!==ext.id.toLowerCase()),ext]);setView('installed');setNotice(`${ext.name} installed.`);}catch(e){setError(String(e));}finally{setBusy('');}}
  function change(next:Extension[]){try{commit(next);setError('');}catch(e){setError(String(e));}}
  const themes=items.filter(x=>x.enabled).flatMap(x=>x.themes.map((t,i)=>({id:themeId(x.id,i),name:t.name})));
  function applyTheme(id:string,name:string){try{onTheme(id);setError('');setNotice(`${name} applied to your workspace and editor.`);}catch(e){setError(String(e));}}
  return <section className="extensions-panel" aria-label="Extension marketplace">
    <div className="extensions-intro"><Package size={25}/><h3>Make room for more.</h3><p>Discover color themes and code snippets from Open VSX.</p></div>
    <div className="extension-tabs"><button className={view==='discover'?'active':''} onClick={()=>setView('discover')}>Discover</button><button className={view==='installed'?'active':''} onClick={()=>setView('installed')}>Installed <span>{items.length}</span></button></div>
    <button className="secondary import-extension" disabled={!!busy} onClick={()=>upload.current?.click()}><Upload size={13}/> Install from VSIX…</button><input ref={upload} type="file" accept=".vsix" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value='';}}/>
    <label className="extension-theme">Editor theme<select aria-label="Extension editor theme" value={theme} onChange={e=>applyTheme(e.target.value,themes.find(t=>t.id===e.target.value)?.name||'Default appearance')}><option value="">Use appearance setting</option>{themes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
    {view==='installed'&&themes.length>0&&<div className="theme-choices"><h4>Apply an installed theme</h4>{themes.map(t=><button className="secondary" key={t.id} disabled={!!busy||theme===t.id} onClick={()=>applyTheme(t.id,t.name)} aria-label={`${theme===t.id?'Applied':'Apply'} ${t.name}`}>{theme===t.id&&<Check size={13}/>}<span>{t.name}</span><small>{theme===t.id?'Applied':'Apply'}</small></button>)}</div>}
    <p className="extension-note">Supports editor colors and snippet suggestions. Language servers, debuggers, icon packs and AI extensions require a VS Code extension host and are not supported yet. Theme syntax colors are approximated.</p>
    {error&&<p className="extension-error" role="alert">{error}</p>}{notice&&<p className="extension-notice" role="status">{notice}</p>}
    {view==='discover'?<><label className="search-input"><Search size={14}/><input aria-label="Search extensions" placeholder="Search extensions…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Extension category" value={category} onChange={e=>setCategory(e.target.value)}><option>Themes</option><option>Snippets</option></select>
      {loading?<p role="status" className="hint">Searching Open VSX…</p>:<div className="extension-list">{results.length===0&&!error&&<p className="hint">No extensions found. Try another search.</p>}{results.map(item=>{const id=`${item.namespace}.${item.name}`;const installed=items.some(x=>x.id.toLowerCase()===id.toLowerCase());return <article className="extension-card" key={id}><div className="extension-title"><Package size={18}/><h4>{item.displayName||item.name}</h4></div><small>{item.namespace} · {item.version}</small><p>{item.description}</p><div className="extension-footer"><small>{(item.downloadCount||0).toLocaleString()} downloads</small><button className="secondary" disabled={!!busy||installed} onClick={()=>void install(item)}>{installed?<Check size={12}/>:<Download size={12}/>}{installed?'Installed':busy===id?'Installing…':'Install'}</button></div></article>;})}</div>}</>:
      <div className="extension-list">{!items.length&&<p className="hint">Your installed extensions will appear here.</p>}{items.map(item=><article className="extension-card" key={item.id}><div className="extension-title"><Package size={18}/><h4>{item.name}</h4></div><small>{item.publisher} · {item.version}</small><p>{item.themes.length} themes · {item.snippets.length} snippets · {item.enabled?'Enabled':'Disabled'}</p><div className="extension-footer"><button className="secondary" disabled={!!busy} onClick={()=>change(items.map(x=>x.id===item.id?{...x,enabled:!x.enabled}:x))}>{item.enabled?'Disable':'Enable'}</button><button className="secondary" disabled={!!busy} onClick={()=>change(items.filter(x=>x.id!==item.id))}>Uninstall</button></div></article>)}</div>}
  </section>;
}
