import {useEffect,useMemo,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Check,ChevronDown,ChevronRight,Clock3,GitCommitHorizontal,Minus,Plus,RefreshCw,RotateCcw} from 'lucide-react';
import {DimensionalIcon} from './DimensionalIcon';

type Change={path:string;index:string;worktree:string};
type Props={status:string;refresh:()=>Promise<void>;openDiff:(path:string)=>Promise<void>;report:(error:unknown)=>void};

export function SourceControl({status,refresh,openDiff,report}:Props){
  const [message,setMessage]=useState('');const [history,setHistory]=useState('');const [busy,setBusy]=useState('');const [historyOpen,setHistoryOpen]=useState(true);const [discard,setDiscard]=useState('');
  const lines=status.split('\n').filter(Boolean);const branch=lines[0]?.startsWith('## ')?lines.shift()!.slice(3).split('...')[0]:'No repository';
  const changes=useMemo<Change[]>(()=>lines.filter(line=>line.length>=3).map(line=>({index:line[0],worktree:line[1],path:line.slice(3).replace(/^"|"$/g,'').split(' -> ').at(-1)!})),[status]);
  const staged=changes.filter(item=>item.index!==' '&&item.index!=='?');const unstaged=changes.filter(item=>item.worktree!==' '||item.index==='?');
  async function loadHistory(){try{setHistory(await invoke<string>('git_log'));}catch{setHistory('');}}
  useEffect(()=>{if(status)void loadHistory();},[status.split('\n')[0]]);
  async function action(command:string,path:string){setBusy(command+path);try{await invoke(command,{path});await refresh();if(command==='git_discard')setDiscard('');}catch(error){report(error);}finally{setBusy('');}}
  async function commit(){if(!message.trim())return;setBusy('commit');try{await invoke<string>('git_commit',{message});setMessage('');await refresh();await loadHistory();}catch(error){report(error);}finally{setBusy('');}}
  const group=(title:string,items:Change[],isStaged:boolean)=><section className="scm-group"><header><span>{title}</span><b>{items.length}</b></header>{items.map(item=><div className="scm-change" key={(isStaged?'s':'u')+item.path}><button className="scm-file" title={'View diff · '+item.path} onClick={()=>void openDiff(item.path)}><DimensionalIcon path={item.path}/><span>{item.path}</span><i>{isStaged?item.index:item.worktree===' '?'U':item.worktree}</i></button><div className="scm-actions">{isStaged?<button title="Unstage change" disabled={!!busy} onClick={()=>void action('git_unstage',item.path)}><Minus size={13}/></button>:<><button title="Stage change" disabled={!!busy} onClick={()=>void action('git_stage',item.path)}><Plus size={13}/></button>{item.index!=='?'&&<button title="Discard change" disabled={!!busy} onClick={()=>setDiscard(item.path)}><RotateCcw size={12}/></button>}</>}</div></div>)}</section>;
  return <div className="source-control"><div className="git-heading"><GitCommitHorizontal size={16}/><b>{branch}</b><button className="icon-button" title="Refresh Git" onClick={()=>void refresh()}><RefreshCw size={14}/></button></div>{branch==='No repository'?<div className="scm-empty">Open a folder containing a Git repository.</div>:<><textarea aria-label="Commit message" placeholder="Message (⌘Enter to commit)" value={message} onChange={event=>setMessage(event.target.value)} onKeyDown={event=>{if((event.metaKey||event.ctrlKey)&&event.key==='Enter')void commit();}}/><button className="scm-commit primary" disabled={!message.trim()||!staged.length||!!busy} onClick={()=>void commit()}><Check size={14}/>Commit {staged.length?`${staged.length} staged`:''}</button>{group('STAGED CHANGES',staged,true)}{group('CHANGES',unstaged,false)}{!changes.length&&<div className="scm-empty"><Check size={18}/>Working tree clean</div>}<section className="scm-history"><button onClick={()=>setHistoryOpen(value=>!value)}>{historyOpen?<ChevronDown size={13}/>:<ChevronRight size={13}/>}<Clock3 size={13}/>RECENT COMMITS</button>{historyOpen&&<div>{history?history.split('\n').map(line=>{const [hash,author,when,...subject]=line.split('\t');return <article key={hash}><code>{hash}</code><span>{subject.join(' ')}</span><small>{author} · {when}</small></article>}):<p>No commits yet.</p>}</div>}</section></>}{discard&&<div className="scm-confirm"><p>Discard changes in <b>{discard}</b>?</p><small>This cannot be undone.</small><div><button onClick={()=>setDiscard('')}>Cancel</button><button className="danger" onClick={()=>void action('git_discard',discard)}>Discard</button></div></div>}</div>;
}
